// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5GEaQiJWjGFgtMeBfEavI83GbiLGx1TA',
    appId: '1:699740699173:web:91ec37d92be19fb65a1dcc',
    messagingSenderId: '699740699173',
    projectId: 'yakalma-yowit',
    authDomain: 'yakalma-yowit.firebaseapp.com',
    storageBucket: 'yakalma-yowit.appspot.com',
    measurementId: 'G-394WEVLFWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Is_ab_Oai8uc7YvoCqtRKz__PnvIcoo',
    appId: '1:699740699173:android:0e7737ee22a0247a5a1dcc',
    messagingSenderId: '699740699173',
    projectId: 'yakalma-yowit',
    storageBucket: 'yakalma-yowit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFOR8B-Jx5G1zoS9KRDzifLNpHs0Mgl1A',
    appId: '1:699740699173:ios:cc32f26343977bbe5a1dcc',
    messagingSenderId: '699740699173',
    projectId: 'yakalma-yowit',
    storageBucket: 'yakalma-yowit.appspot.com',
    iosBundleId: 'khalil.yakalma.app.testProject',
  );
}
